DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AccountType') THEN
    CREATE TYPE "AccountType" AS ENUM ('INDIVIDUAL', 'PROFESSIONAL', 'ASSOCIATION');
  END IF;
END $$;

ALTER TABLE "UserProfile"
ADD COLUMN IF NOT EXISTS "accountType" "AccountType" NOT NULL DEFAULT 'INDIVIDUAL';
