-- Homepage redesign editable blocks
ALTER TABLE "HomepageSettings"
  ADD COLUMN IF NOT EXISTS "heroButtonLink" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "heroTitleTag" TEXT NOT NULL DEFAULT 'h1',
  ADD COLUMN IF NOT EXISTS "heroSubtitleTag" TEXT NOT NULL DEFAULT 'p',
  ADD COLUMN IF NOT EXISTS "heroButtonStyle" TEXT NOT NULL DEFAULT 'primary',
  ADD COLUMN IF NOT EXISTS "feature1Icon" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature1Title" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature1Text" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature2Icon" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature2Title" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature2Text" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature3Icon" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature3Title" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "feature3Text" TEXT NOT NULL DEFAULT '';

INSERT INTO "HomepageSettings" (
  "id",
  "heroTitle",
  "heroSubtitle",
  "heroButtonLabel",
  "heroButtonUrl",
  "heroButtonLink",
  "heroIllustrationUrl",
  "feature1Icon",
  "feature1Title",
  "feature1Text",
  "feature2Icon",
  "feature2Title",
  "feature2Text",
  "feature3Icon",
  "feature3Title",
  "feature3Text",
  "heroTitleTag",
  "heroSubtitleTag",
  "heroButtonStyle"
) VALUES (
  1,
  'L’aide à la comptabilité des TPE au meilleur prix.',
  'Centralisez votre gestion comptable simplement, soyez toujours à jour, et concentrez-vous sur l’essentiel : votre activité.',
  'Découvrir nos logiciels',
  '#',
  '#',
  'https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=1200&q=80',
  'check',
  'Outils simples & complets',
  'Des outils intuitifs pour suivre votre comptabilité au quotidien.',
  'layers',
  'Tarifs transparents',
  'Des offres claires et sans surprise, adaptées aux TPE.',
  'support',
  'Support dédié & réactif',
  'Une équipe qui répond vite pour vous accompagner.',
  'h1',
  'p',
  'primary'
) ON CONFLICT ("id") DO UPDATE SET
  "heroTitle" = EXCLUDED."heroTitle",
  "heroSubtitle" = EXCLUDED."heroSubtitle",
  "heroButtonLabel" = EXCLUDED."heroButtonLabel",
  "heroButtonUrl" = EXCLUDED."heroButtonUrl",
  "heroButtonLink" = EXCLUDED."heroButtonLink",
  "heroIllustrationUrl" = EXCLUDED."heroIllustrationUrl",
  "feature1Icon" = EXCLUDED."feature1Icon",
  "feature1Title" = EXCLUDED."feature1Title",
  "feature1Text" = EXCLUDED."feature1Text",
  "feature2Icon" = EXCLUDED."feature2Icon",
  "feature2Title" = EXCLUDED."feature2Title",
  "feature2Text" = EXCLUDED."feature2Text",
  "feature3Icon" = EXCLUDED."feature3Icon",
  "feature3Title" = EXCLUDED."feature3Title",
  "feature3Text" = EXCLUDED."feature3Text",
  "heroTitleTag" = EXCLUDED."heroTitleTag",
  "heroSubtitleTag" = EXCLUDED."heroSubtitleTag",
  "heroButtonStyle" = EXCLUDED."heroButtonStyle";
